name: 📝 文档问题
description: 报告文档相关的问题
title: '[文档]: '
labels: ['documentation']
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间来改进我们的文档!

  - type: dropdown
    id: type
    attributes:
      label: 文档问题类型
      options:
        - 缺失文档
        - 不清晰的文档
        - 不正确的文档
        - 需要翻译
        - 其他
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: 文档位置
      description: 您所指的文档在哪里?
      placeholder: 例如 README.md, 贡献指南等

  - type: textarea
    id: description
    attributes:
      label: 描述
      description: 请描述文档存在的问题
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: 建议修改
      description: 如果您有具体的建议来改进文档,请在此提供
