name: 📝 Documentation Issue
description: Report issues with documentation
title: '[Docs]: '
labels: ['documentation']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Type of documentation issue
      options:
        - Missing documentation
        - Unclear documentation
        - Incorrect documentation
        - Translation needed
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation you're referring to?
      placeholder: e.g. README.md, Contributing Guide, etc.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the issue with the documentation
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Changes
      description: If you have specific suggestions for how to improve the documentation, please provide them here
